//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVMODELFİRST
{
    using System;
    using System.Collections.Generic;
    
    public partial class kanal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kanal()
        {
            this.yayin = new HashSet<yayin>();
        }
    
        public int kanalid { get; set; }
        public string kanaladi { get; set; }
        public decimal ciro { get; set; }
        public string adres { get; set; }
        public double reyting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yayin> yayin { get; set; }
    }
}
