//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVMODELFİRST
{
    using System;
    using System.Collections.Generic;
    
    public partial class yayin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yayin()
        {
            this.sorumlu = new HashSet<sorumlu>();
        }
    
        public int yayinid { get; set; }
        public string yayinadi { get; set; }
        public string yayintarihi { get; set; }
        public double reyting { get; set; }
        public int kanalid { get; set; }
    
        public virtual kanal kanal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sorumlu> sorumlu { get; set; }
    }
}
